use bevy_ecs::prelude::*;
use glam::DVec3;
use kiddo::KdTree;

use crate::components::spatial::BoundingRadius;
use crate::core::config::UniverseConfig;
use crate::core::coordinates::{displacement, LocalPosition, Sector};

/// Candidate collision pair from the broadphase.
#[derive(Debug, Clone)]
pub struct CandidatePair {
    pub entity_a: Entity,
    pub entity_b: Entity,
}

/// Resource holding the KD-Tree for spatial queries.
#[derive(Resource)]
pub struct KdTreeBroadphase {
    pub tree: KdTree<f64, 3>,
    pub entities: Vec<Entity>,
}

impl Default for KdTreeBroadphase {
    fn default() -> Self {
        Self {
            tree: KdTree::new(),
            entities: Vec::new(),
        }
    }
}

/// Extracts entities with `BoundingRadius` and builds the broadphase tree.
pub fn build_broadphase_system(
    query: Query<(Entity, &Sector, &LocalPosition, &BoundingRadius)>,
    config: Res<UniverseConfig>,
    mut broadphase: ResMut<KdTreeBroadphase>,
) {
    let sector_size = config.sector_size;
    let mut tree = KdTree::new();
    let mut entities = Vec::new();

    let reference_sector = Sector::ORIGIN;
    let reference_local = LocalPosition::ZERO;

    for (entity, sector, local, _) in query.iter() {
        let pos = displacement(&reference_sector, &reference_local, sector, local, sector_size);
        tree.add(&[pos.x, pos.y, pos.z], entities.len() as u64);
        entities.push(entity);
    }

    broadphase.tree = tree;
    broadphase.entities = entities;
}

/// Resource to hold the list of candidate pairs generated by broadphase.
#[derive(Resource, Default)]
pub struct CandidatePairs(pub Vec<CandidatePair>);

/// Queries the broadphase tree to find candidate pairs.
pub fn broadphase_query_system(
    query: Query<(Entity, &Sector, &LocalPosition, &BoundingRadius)>,
    config: Res<UniverseConfig>,
    broadphase: Res<KdTreeBroadphase>,
    mut candidate_pairs: ResMut<CandidatePairs>,
) {
    let sector_size = config.sector_size;
    let reference_sector = Sector::ORIGIN;
    let reference_local = LocalPosition::ZERO;

    candidate_pairs.0.clear();

    for (entity_a, sector_a, local_a, radius_a) in query.iter() {
        let pos_a = displacement(&reference_sector, &reference_local, sector_a, local_a, sector_size);
        
        // Find all elements within the radius. We just search within double the radius to catch everything.
        let search_radius = radius_a.0 * 4.0; // Over-approximate for now. 
        let search_radius_sq = search_radius * search_radius;

        let within = broadphase.tree.within::<kiddo::SquaredEuclidean>(&[pos_a.x, pos_a.y, pos_a.z], search_radius_sq);

        for neighbor in within {
            let entity_b_idx = neighbor.item as usize;
            let entity_b = broadphase.entities[entity_b_idx];

            if entity_a != entity_b {
                // To avoid duplicate pairs, we only record if entity_a < entity_b
                if entity_a < entity_b {
                    candidate_pairs.0.push(CandidatePair {
                        entity_a,
                        entity_b,
                    });
                }
            }
        }
    }
}
